data_acquisition:
  data_dirpath: './data'
  save_to_csv: true
  send_to_db: true

camera:
  camera_index: 0
  width: 320
  height: 240
  fps: 30

db:
  url: 'http://localhost:8086'
  token: 'MfcFIOXcEGm5AdL_SFmoS5kFH0LZm0Escl93KvUUe-JXSa81UN0NDqUh2VQ_vzxMidEztZenFzKmMiYQYgmdSg=='
  org: 'RealtimeCsi'
  bucket: 'image_bucket'